# Generated by Django 5.2b1 on 2025-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_player',
            field=models.BooleanField(default=False),
        ),
    ]
